### ISSUE TITLE
Enable the ability to disable models

### ISSUE THREAD

**Issue by Tom-Neverwinter** [RandomInternetPreson/Lucid_Vision#5]
Can we forego the loading of models until we have a menu?
I dont want to have 50GB of models when I only need one. bunny or phi or deepseekvl

PaliGemma seems to create this error as I didnt download and add the model

```
Python version is above 3.10, patching the collections module.
21:34:08-300643 ERROR    Failed to load the extension "Lucid_Vision".
Traceback (most recent call last):
  File "C:\Users\Tom_N\Desktop\text-generation-webui\modules\extensions.py", line 37, in load_extensions
    extension = importlib.import_module(f"extensions.{name}.script")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tom_N\Desktop\text-generation-webui\installer_files\env\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Tom_N\Desktop\text-generation-webui\extensions\Lucid_Vision\script.py", line 12, in <module>
    from transformers import AutoModelForCausalLM, AutoModel, AutoTokenizer, AutoProcessor, \
ImportError: cannot import name 'PaliGemmaForConditionalGeneration' from 'transformers' (C:\Users\Tom_N\Desktop\text-generation-webui\installer_files\env\Lib\site-packages\transformers\__init__.py)
```

**Comment by RandomInternetPreson** [comment]
Oh, probably because you didn't change the "default_vision_model" in the config.json file. You'll need at least one model downloaded so the extension has a model to use; then you make that model your default_vision_model.  Let me know if this fixes the problem.

**Comment by Tom-Neverwinter** [comment]
I had several models installed and configured
